### PR TITLE
Add GitHub Action for release

### PR DESCRIPTION
**Pull request by chrisvire**
This can be merged once the design pull request is merged (which includes changes for .gitignore and .goreleaser.yaml).

### CODE REVIEW

**Comment by Davideo37** [comment]
Design was merged https://github.com/gordon-cs/appbuilder-storybuilder/commit/a78caed3970dc1a90828ea15bb4937c1e4eaecf8

**Comment by chrisvire** [comment]
@Davideo37 With this change, you could change the documentation to state that just making a tag will cause a build to be produced by GitHub Actions.

**Comment by Davideo37** [comment]
I will update that ASAP!

**Comment by chrisvire** [comment]
@Davideo37 Could you push a label to fire the GitHub Action?

**Comment by Davideo37** [comment]
Just did so, it says our program doesn't contain a main function, but it does so I'm not sure what happened

**Comment by Davideo37** [comment]
@chrisvire It may have something to do with the Github action not having a .goreleaser.yaml config file so it uses the default settings. There is a file in the main branch tho, so I'm not sure why it wouldn't have one. I can generate a release manually, but the GitHub action seems to crash every time

**Comment by chrisvire** [comment]
@Davideo37 the github action yaml is pointing at the wrong directory.  I will submit a PR.

**Pull request merged**
